/**
 * The contents of this file are subject to the OpenMRS Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://license.openmrs.org
 *
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
 * License for the specific language governing rights and limitations
 * under the License.
 *
 * Copyright (C) OpenMRS, LLC.  All Rights Reserved.
 */
package org.openmrs.module.orderextension;

import java.io.Serializable;

import org.openmrs.BaseOpenmrsObject;
import org.openmrs.OpenmrsObject;
import org.openmrs.util.OpenmrsUtil;

/**
 * This represents a single member within an ExtendedOrderSet
 */
public abstract class ExtendedOrderSetMember
		extends BaseOpenmrsObject implements Serializable, Comparable<ExtendedOrderSetMember> {
	
	public static final long serialVersionUID = 1L;
	
	/**
	 * Default Constructor
	 */
	public ExtendedOrderSetMember() {}
	
	/**
	 * The primary key id for this ExtendedOrderSet when saved
	 */
	private Integer id;
	
	/**
	 * The ExtendedOrderSet that this member belongs to
	 */
	private ExtendedOrderSet orderSet;
	
	/**
	 * Represents a descriptive title for this ExtendedOrderSetMember
	 */
	private String title;
	
	/**
	 * Represents additional information that may be presented to the
	 * user when they are considering or viewing this ExtendedOrderSetMember
	 */
	private String comment;
	
	/**
	 * If true, this indicates that this member should be ordered by default
	 * e.g., an order set may contain a list of common post-surgical analgesics 
	 * with the preferred treatment already selected as the one to be.
	 */
	private boolean selected;
	
	/**
	 * If non-null, indicates that the start date of the Orders generated by
	 * this particular ExtendedOrderSetMember should start this number of days after
	 * the start date chosen for the parent ExtendedOrderGroup.  If null, this indicates that
	 * the Order should start on the start date of the parent ExtendedOrderGroup
	 */
	private Integer relativeStartDay;
	
	/**
	 * If non-null, this indicates whether the Orders generated by this particular
	 * ExtendedOrderSetMember should auto-expire after a certain number of days.
	 */
	private Integer lengthInDays;
	
	/**
	 * Provides a mechanism for describing the Orders to be generated by this
	 * particular ExtendedOrderSetMember in more detail, including default values and restrictions
	 */
	private String template;
	
	/**
	 * This field should be used to determine the order of a particular order set member
	 * in relation to another within an Order Set.
	 */
	private Integer sortWeight;
	
	//***** INSTANCE METHODS *****
	
	/**
	 * @see Comparable#compareTo(Object)
	 */
	@Override
	public int compareTo(ExtendedOrderSetMember that) {
		int ret = 0;
		if (this.getOrderSet() != null && that.getOrderSet() != null) {
			ret = OpenmrsUtil.compareWithNullAsGreatest(this.getOrderSet().getId(), that.getOrderSet().getId());
		}
		if (ret == 0) {
			ret = OpenmrsUtil.compareWithNullAsGreatest(this.getSortWeight(), that.getSortWeight());
		}
		if (ret == 0) {
			ret = OpenmrsUtil.compareWithNullAsGreatest(this.getId(), that.getId());
		}
		if (ret == 0) {
			ret = OpenmrsUtil.compareWithNullAsGreatest(this.getUuid(), that.getUuid());
		}
		return ret;
	}
	
	/**
	 * @see OpenmrsObject#getId()
	 */
	public Integer getId() {
		return id;
	}
	
	/**
	 * @see OpenmrsObject#setId(Integer)
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the orderSet
	 */
	public ExtendedOrderSet getOrderSet() {
		return orderSet;
	}

	/**
	 * @param orderSet the orderSet to set
	 */
	public void setOrderSet(ExtendedOrderSet orderSet) {
		this.orderSet = orderSet;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * @return the comment
	 */
	public String getComment() {
		return comment;
	}

	/**
	 * @param comment the comment to set
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}

	/**
	 * @return the selected
	 */
	public boolean isSelected() {
		return selected;
	}

	/**
	 * @param selected the selected to set
	 */
	public void setSelected(boolean selected) {
		this.selected = selected;
	}

	/**
	 * @return the relativeStartDay
	 */
	public Integer getRelativeStartDay() {
		return relativeStartDay;
	}

	/**
	 * @param relativeStartDay the relativeStartDay to set
	 */
	public void setRelativeStartDay(Integer relativeStartDay) {
		this.relativeStartDay = relativeStartDay;
	}

	/**
	 * @return the lengthInDays
	 */
	public Integer getLengthInDays() {
		return lengthInDays;
	}

	/**
	 * @param lengthInDays the lengthInDays to set
	 */
	public void setLengthInDays(Integer lengthInDays) {
		this.lengthInDays = lengthInDays;
	}

	/**
	 * @return the template
	 */
	public String getTemplate() {
		return template;
	}

	/**
	 * @param template the template to set
	 */
	public void setTemplate(String template) {
		this.template = template;
	}

	/**
	 * @return the sortWeight
	 */
	public Integer getSortWeight() {
		return sortWeight;
	}

	/**
	 * @param sortWeight the sortWeight to set
	 */
	public void setSortWeight(Integer sortWeight) {
		this.sortWeight = sortWeight;
	}
}
